# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_InputPath = QtWidgets.QLabel(self.centralwidget)
        self.label_InputPath.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_InputPath.setScaledContents(False)
        self.label_InputPath.setWordWrap(False)
        self.label_InputPath.setObjectName("label_InputPath")
        self.edit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_input.setEnabled(True)
        self.edit_input.setGeometry(QtCore.QRect(10, 30, 291, 22))
        self.edit_input.setReadOnly(True)
        self.edit_input.setObjectName("edit_input")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 311, 671))
        self.groupBox.setObjectName("groupBox")
        self.label_InputPath_2 = QtWidgets.QLabel(self.groupBox)
        self.label_InputPath_2.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.label_InputPath_2.setScaledContents(False)
        self.label_InputPath_2.setWordWrap(False)
        self.label_InputPath_2.setObjectName("label_InputPath_2")
        self.edit_styleInput = QtWidgets.QLineEdit(self.groupBox)
        self.edit_styleInput.setEnabled(True)
        self.edit_styleInput.setGeometry(QtCore.QRect(10, 50, 261, 22))
        self.edit_styleInput.setReadOnly(True)
        self.edit_styleInput.setObjectName("edit_styleInput")
        self.btn_inputStyle = QtWidgets.QPushButton(self.groupBox)
        self.btn_inputStyle.setGeometry(QtCore.QRect(10, 80, 93, 28))
        self.btn_inputStyle.setObjectName("btn_inputStyle")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 270, 135, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.optimizer_combo = QtWidgets.QComboBox(self.layoutWidget)
        self.optimizer_combo.setObjectName("optimizer_combo")
        self.optimizer_combo.addItem("")
        self.optimizer_combo.addItem("")
        self.horizontalLayout_5.addWidget(self.optimizer_combo)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 150, 179, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.InitImageType_Combo = QtWidgets.QComboBox(self.layoutWidget1)
        self.InitImageType_Combo.setObjectName("InitImageType_Combo")
        self.InitImageType_Combo.addItem("")
        self.InitImageType_Combo.addItem("")
        self.InitImageType_Combo.addItem("")
        self.horizontalLayout.addWidget(self.InitImageType_Combo)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 210, 186, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.content_loss_func_combo = QtWidgets.QComboBox(self.layoutWidget2)
        self.content_loss_func_combo.setMaxCount(10)
        self.content_loss_func_combo.setMinimumContentsLength(0)
        self.content_loss_func_combo.setObjectName("content_loss_func_combo")
        self.content_loss_func_combo.addItem("")
        self.content_loss_func_combo.addItem("")
        self.content_loss_func_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.content_loss_func_combo)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 240, 132, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pool_args_combo = QtWidgets.QComboBox(self.layoutWidget3)
        self.pool_args_combo.setObjectName("pool_args_combo")
        self.pool_args_combo.addItem("")
        self.pool_args_combo.addItem("")
        self.horizontalLayout_3.addWidget(self.pool_args_combo)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 181, 204, 23))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ColorConvertType_Combo = QtWidgets.QComboBox(self.layoutWidget4)
        self.ColorConvertType_Combo.setObjectName("ColorConvertType_Combo")
        self.ColorConvertType_Combo.addItem("")
        self.ColorConvertType_Combo.addItem("")
        self.ColorConvertType_Combo.addItem("")
        self.ColorConvertType_Combo.addItem("")
        self.horizontalLayout_4.addWidget(self.ColorConvertType_Combo)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 120, 131, 23))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.Device_Combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.Device_Combo.setObjectName("Device_Combo")
        self.Device_Combo.addItem("")
        self.Device_Combo.addItem("")
        self.horizontalLayout_6.addWidget(self.Device_Combo)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 320, 276, 24))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.line_styleImgWeights = QtWidgets.QLineEdit(self.layoutWidget5)
        self.line_styleImgWeights.setObjectName("line_styleImgWeights")
        self.horizontalLayout_7.addWidget(self.line_styleImgWeights)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 360, 94, 20))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setScaledContents(False)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.stylemask_check = QtWidgets.QCheckBox(self.layoutWidget6)
        self.stylemask_check.setText("")
        self.stylemask_check.setObjectName("stylemask_check")
        self.horizontalLayout_8.addWidget(self.stylemask_check)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 400, 117, 20))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setScaledContents(False)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.originalColor_check = QtWidgets.QCheckBox(self.layoutWidget7)
        self.originalColor_check.setText("")
        self.originalColor_check.setChecked(False)
        self.originalColor_check.setObjectName("originalColor_check")
        self.horizontalLayout_9.addWidget(self.originalColor_check)
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 450, 156, 24))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setScaledContents(False)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.iteration_spin = QtWidgets.QSpinBox(self.layoutWidget8)
        self.iteration_spin.setMaximum(10000)
        self.iteration_spin.setProperty("value", 100)
        self.iteration_spin.setObjectName("iteration_spin")
        self.horizontalLayout_10.addWidget(self.iteration_spin)
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 500, 189, 24))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setScaledContents(False)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.learingrate_doubleSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.learingrate_doubleSpin.setDecimals(6)
        self.learingrate_doubleSpin.setProperty("value", 0.001)
        self.learingrate_doubleSpin.setObjectName("learingrate_doubleSpin")
        self.horizontalLayout_11.addWidget(self.learingrate_doubleSpin)
        self.layoutWidget10 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 550, 120, 24))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setScaledContents(False)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.maxSize_spin = QtWidgets.QSpinBox(self.layoutWidget10)
        self.maxSize_spin.setMaximum(8192)
        self.maxSize_spin.setProperty("value", 512)
        self.maxSize_spin.setObjectName("maxSize_spin")
        self.horizontalLayout_12.addWidget(self.maxSize_spin)
        self.layoutWidget11 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget11.setGeometry(QtCore.QRect(30, 590, 226, 61))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setScaledContents(False)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.outname_line = QtWidgets.QLineEdit(self.layoutWidget11)
        self.outname_line.setObjectName("outname_line")
        self.horizontalLayout_13.addWidget(self.outname_line)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.btn_styles_convert = QtWidgets.QPushButton(self.layoutWidget11)
        self.btn_styles_convert.setObjectName("btn_styles_convert")
        self.verticalLayout.addWidget(self.btn_styles_convert)
        self.btn_inputImage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_inputImage.setGeometry(QtCore.QRect(320, 30, 93, 28))
        self.btn_inputImage.setObjectName("btn_inputImage")
        self.lab_originalImg = QtWidgets.QLabel(self.centralwidget)
        self.lab_originalImg.setGeometry(QtCore.QRect(330, 220, 256, 256))
        self.lab_originalImg.setStyleSheet("background:rgb(255, 255, 255)")
        self.lab_originalImg.setText("")
        self.lab_originalImg.setObjectName("lab_originalImg")
        self.lab_style_img = QtWidgets.QLabel(self.centralwidget)
        self.lab_style_img.setGeometry(QtCore.QRect(1210, 50, 128, 128))
        self.lab_style_img.setStyleSheet("background:rgb(255, 255, 255)")
        self.lab_style_img.setText("")
        self.lab_style_img.setObjectName("lab_style_img")
        self.lab_styleImg_multi = QtWidgets.QLabel(self.centralwidget)
        self.lab_styleImg_multi.setGeometry(QtCore.QRect(610, 50, 512, 128))
        self.lab_styleImg_multi.setStyleSheet("")
        self.lab_styleImg_multi.setText("")
        self.lab_styleImg_multi.setObjectName("lab_styleImg_multi")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.optimizer_combo.setCurrentIndex(0)
        self.content_loss_func_combo.setCurrentIndex(0)
        self.pool_args_combo.setCurrentIndex(0)
        self.Device_Combo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_InputPath.setText(_translate("MainWindow", "<b>ImagePath</b>"))
        self.groupBox.setTitle(_translate("MainWindow", "StyleGroup"))
        self.label_InputPath_2.setText(_translate("MainWindow", "<b>StylePath</b>"))
        self.btn_inputStyle.setText(_translate("MainWindow", "ImportStyle"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Optimizer</span></p></body></html>"))
        self.optimizer_combo.setItemText(0, _translate("MainWindow", "lbfgs"))
        self.optimizer_combo.setItemText(1, _translate("MainWindow", "adam"))
        self.label_3.setText(_translate("MainWindow", "<b>InitImageType</b>"))
        self.InitImageType_Combo.setItemText(0, _translate("MainWindow", "content"))
        self.InitImageType_Combo.setItemText(1, _translate("MainWindow", "random"))
        self.InitImageType_Combo.setItemText(2, _translate("MainWindow", "style"))
        self.label.setText(_translate("MainWindow", "<b>ContentLossFunction</b>"))
        self.content_loss_func_combo.setCurrentText(_translate("MainWindow", "1"))
        self.content_loss_func_combo.setItemText(0, _translate("MainWindow", "1"))
        self.content_loss_func_combo.setItemText(1, _translate("MainWindow", "2"))
        self.content_loss_func_combo.setItemText(2, _translate("MainWindow", "3"))
        self.label_2.setText(_translate("MainWindow", "<b>Pool_Args</b>"))
        self.pool_args_combo.setItemText(0, _translate("MainWindow", "avg"))
        self.pool_args_combo.setItemText(1, _translate("MainWindow", "max"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ColorConvertType</span></p></body></html>"))
        self.ColorConvertType_Combo.setItemText(0, _translate("MainWindow", "yuv"))
        self.ColorConvertType_Combo.setItemText(1, _translate("MainWindow", "ycrb"))
        self.ColorConvertType_Combo.setItemText(2, _translate("MainWindow", "luv"))
        self.ColorConvertType_Combo.setItemText(3, _translate("MainWindow", "lab"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Device</span></p></body></html>"))
        self.Device_Combo.setItemText(0, _translate("MainWindow", "CPU"))
        self.Device_Combo.setItemText(1, _translate("MainWindow", "GPU"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">StyleImgWeights</span></p></body></html>"))
        self.line_styleImgWeights.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">StyleMask</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">OriginalColor</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">MaxIteration</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">LearingRate</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">MaxSize</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">OutName</span></p></body></html>"))
        self.outname_line.setText(_translate("MainWindow", "style"))
        self.btn_styles_convert.setText(_translate("MainWindow", "Convert"))
        self.btn_inputImage.setText(_translate("MainWindow", "Import"))

