# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_InputPath = QtWidgets.QLabel(self.centralwidget)
        self.label_InputPath.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_InputPath.setScaledContents(False)
        self.label_InputPath.setWordWrap(False)
        self.label_InputPath.setObjectName("label_InputPath")
        self.edit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_input.setEnabled(True)
        self.edit_input.setGeometry(QtCore.QRect(10, 30, 291, 22))
        self.edit_input.setReadOnly(True)
        self.edit_input.setObjectName("edit_input")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 301, 501))
        self.groupBox.setObjectName("groupBox")
        self.label_InputPath_2 = QtWidgets.QLabel(self.groupBox)
        self.label_InputPath_2.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.label_InputPath_2.setScaledContents(False)
        self.label_InputPath_2.setWordWrap(False)
        self.label_InputPath_2.setObjectName("label_InputPath_2")
        self.edit_styleInput = QtWidgets.QLineEdit(self.groupBox)
        self.edit_styleInput.setEnabled(True)
        self.edit_styleInput.setGeometry(QtCore.QRect(10, 50, 261, 22))
        self.edit_styleInput.setReadOnly(True)
        self.edit_styleInput.setObjectName("edit_styleInput")
        self.btn_inputStyle = QtWidgets.QPushButton(self.groupBox)
        self.btn_inputStyle.setGeometry(QtCore.QRect(10, 80, 93, 28))
        self.btn_inputStyle.setObjectName("btn_inputStyle")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 240, 132, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.pool_args_combo_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.pool_args_combo_2.setObjectName("pool_args_combo_2")
        self.pool_args_combo_2.addItem("")
        self.pool_args_combo_2.addItem("")
        self.horizontalLayout_5.addWidget(self.pool_args_combo_2)
        self.btn_styles_convert = QtWidgets.QPushButton(self.groupBox)
        self.btn_styles_convert.setGeometry(QtCore.QRect(10, 300, 93, 28))
        self.btn_styles_convert.setObjectName("btn_styles_convert")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 120, 179, 23))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.InitImageType_Combo = QtWidgets.QComboBox(self.widget)
        self.InitImageType_Combo.setObjectName("InitImageType_Combo")
        self.InitImageType_Combo.addItem("")
        self.InitImageType_Combo.addItem("")
        self.InitImageType_Combo.addItem("")
        self.horizontalLayout.addWidget(self.InitImageType_Combo)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(10, 180, 186, 23))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.content_loss_func_combo = QtWidgets.QComboBox(self.widget1)
        self.content_loss_func_combo.setMaxCount(10)
        self.content_loss_func_combo.setMinimumContentsLength(0)
        self.content_loss_func_combo.setObjectName("content_loss_func_combo")
        self.content_loss_func_combo.addItem("")
        self.content_loss_func_combo.addItem("")
        self.content_loss_func_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.content_loss_func_combo)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(10, 210, 132, 23))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pool_args_combo = QtWidgets.QComboBox(self.widget2)
        self.pool_args_combo.setObjectName("pool_args_combo")
        self.pool_args_combo.addItem("")
        self.pool_args_combo.addItem("")
        self.horizontalLayout_3.addWidget(self.pool_args_combo)
        self.widget3 = QtWidgets.QWidget(self.groupBox)
        self.widget3.setGeometry(QtCore.QRect(11, 151, 204, 23))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget3)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ColorConvertType_Combo = QtWidgets.QComboBox(self.widget3)
        self.ColorConvertType_Combo.setObjectName("ColorConvertType_Combo")
        self.ColorConvertType_Combo.addItem("")
        self.ColorConvertType_Combo.addItem("")
        self.ColorConvertType_Combo.addItem("")
        self.ColorConvertType_Combo.addItem("")
        self.horizontalLayout_4.addWidget(self.ColorConvertType_Combo)
        self.btn_inputImage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_inputImage.setGeometry(QtCore.QRect(320, 30, 93, 28))
        self.btn_inputImage.setObjectName("btn_inputImage")
        self.lab_originalImg = QtWidgets.QLabel(self.centralwidget)
        self.lab_originalImg.setGeometry(QtCore.QRect(330, 200, 256, 256))
        self.lab_originalImg.setStyleSheet("background:rgb(255, 255, 255)")
        self.lab_originalImg.setText("")
        self.lab_originalImg.setObjectName("lab_originalImg")
        self.lab_style_img = QtWidgets.QLabel(self.centralwidget)
        self.lab_style_img.setGeometry(QtCore.QRect(810, 50, 128, 128))
        self.lab_style_img.setStyleSheet("background:rgb(255, 255, 255)")
        self.lab_style_img.setText("")
        self.lab_style_img.setObjectName("lab_style_img")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pool_args_combo_2.setCurrentIndex(0)
        self.content_loss_func_combo.setCurrentIndex(0)
        self.pool_args_combo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_InputPath.setText(_translate("MainWindow", "<b>ImagePath</b>"))
        self.groupBox.setTitle(_translate("MainWindow", "StyleGroup"))
        self.label_InputPath_2.setText(_translate("MainWindow", "<b>StylePath</b>"))
        self.btn_inputStyle.setText(_translate("MainWindow", "ImportStyle"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Optimizer</span></p></body></html>"))
        self.pool_args_combo_2.setItemText(0, _translate("MainWindow", "lbfgs"))
        self.pool_args_combo_2.setItemText(1, _translate("MainWindow", "adam"))
        self.btn_styles_convert.setText(_translate("MainWindow", "Convert"))
        self.label_3.setText(_translate("MainWindow", "<b>InitImageType</b>"))
        self.InitImageType_Combo.setItemText(0, _translate("MainWindow", "content"))
        self.InitImageType_Combo.setItemText(1, _translate("MainWindow", "random"))
        self.InitImageType_Combo.setItemText(2, _translate("MainWindow", "style"))
        self.label.setText(_translate("MainWindow", "<b>ContentLossFunction</b>"))
        self.content_loss_func_combo.setCurrentText(_translate("MainWindow", "1"))
        self.content_loss_func_combo.setItemText(0, _translate("MainWindow", "1"))
        self.content_loss_func_combo.setItemText(1, _translate("MainWindow", "2"))
        self.content_loss_func_combo.setItemText(2, _translate("MainWindow", "3"))
        self.label_2.setText(_translate("MainWindow", "<b>Pool_Args</b>"))
        self.pool_args_combo.setItemText(0, _translate("MainWindow", "avg"))
        self.pool_args_combo.setItemText(1, _translate("MainWindow", "max"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ColorConvertType</span></p></body></html>"))
        self.ColorConvertType_Combo.setItemText(0, _translate("MainWindow", "yuv"))
        self.ColorConvertType_Combo.setItemText(1, _translate("MainWindow", "ycrb"))
        self.ColorConvertType_Combo.setItemText(2, _translate("MainWindow", "luv"))
        self.ColorConvertType_Combo.setItemText(3, _translate("MainWindow", "lab"))
        self.btn_inputImage.setText(_translate("MainWindow", "Import"))

